name = "ouija-genie"
main = "src/index.js"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

# Optional: Environment variables
[vars]
API_VERSION = "1.0.0"

# Note: Custom domains are configured in Cloudflare dashboard, not in wrangler.toml
# These routes will be added after deployment via the dashboard